package pap;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author user
 */
public class WriteReviewGUII extends javax.swing.JFrame {

    private final DefaultTableModel tableModel2;
    private final ReviewManager reviewManager;
    private static final String DB_URL = "jdbc:mysql://localhost:3306/restaurant_db";
    private static final String DB_USERNAME = "root";
    private static final String DB_PASSWORD = "Ceah3007";

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DB_URL, DB_USERNAME, DB_PASSWORD);
    }

    public WriteReviewGUII() {
        initComponents();

        tableModel2 = (DefaultTableModel) tblOutput2.getModel();
        reviewManager = new ReviewManager(tableModel2);

        // Call the refreshTable() method to populate the JTable with data from the database
        try {
            reviewManager.updateTableData(tableModel2);
        } catch (SQLException ex) {
            System.out.println("Error updating table data: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        txtReviewerName = new javax.swing.JTextField();
        txtReview = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutput2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        lblAverageRating = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 42, 204, 31));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel2.setText("Restaurant Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 91, 139, 39));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel3.setText("Reviewer Name: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 144, 120, 25));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel4.setText("Review:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 189, 139, 31));
        getContentPane().add(txtRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 96, 317, -1));
        getContentPane().add(txtReviewerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 142, 317, -1));
        getContentPane().add(txtReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 190, 317, -1));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 279, -1, -1));

        tblOutput2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblOutput2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Restaurant Name", "Reviewer Name", "Review", "Rating"
            }
        ));
        jScrollPane1.setViewportView(tblOutput2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 490, 200));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N
        jLabel5.setText("Rating:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 235, 62, 22));
        getContentPane().add(txtRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 232, 317, -1));

        lblAverageRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAverageRatingActionPerformed(evt);
            }
        });
        getContentPane().add(lblAverageRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 550, 462, 115));

        btnHome.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 683, -1, 22));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Untitled (781 × 712px) (640 × 670px) (604 × 779px).png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 604, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void searchAndUpdateTable(String keyword) {
        // Clear the table first
        tableModel2.setRowCount(0);

        // Perform the search in the database using the keyword
        try (Connection conn = getConnection()) {
            String sql = "SELECT * FROM restaurant WHERE name LIKE ?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, "%" + keyword + "%");
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                String name = resultSet.getString("name");
                String location = resultSet.getString("location");
                String cuisine = resultSet.getString("cuisine");
                double rating = resultSet.getDouble("rating");
                String comments = resultSet.getString("comments");

                // Add the retrieved data to the tableModel
                Object[] rowData = {name, location, cuisine, rating, comments};
                tableModel2.addRow(rowData);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error searching restaurant: " + ex.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    String restaurantName = txtRestaurantName.getText();
    String reviewerName = txtReviewerName.getText();
    String review = txtReview.getText();
    double rating = Double.parseDouble(txtRating.getText());

    try {
        Connection conn = getConnection();
        String query = "INSERT INTO review (restaurantName, reviewerName, review, rating) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, restaurantName);
        pst.setString(2, reviewerName);
        pst.setString(3, review);
        pst.setDouble(4, rating);

        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Review added successfully!");
        }

        pst.close();
        conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

    // Update the average rating after adding the review
    double averageRating = reviewManager.getAverageRatingForRestaurant(restaurantName);
    lblAverageRating.setText("Average Rating for " + restaurantName + ": " + averageRating);

    // Refresh the table with the updated data
    try {
        reviewManager.updateTableData(tableModel2);
    } catch (SQLException ex) {
        System.out.println("Error updating table data: " + ex.getMessage());
    }

    // Clear input fields
    txtRestaurantName.setText("");
    txtReviewerName.setText("");
    txtReview.setText("");
    txtRating.setText("");          
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void lblAverageRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAverageRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAverageRatingActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        HomePageGUI d = new HomePageGUI();
        d.show();
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WriteReviewGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WriteReviewGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WriteReviewGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WriteReviewGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WriteReviewGUII().setVisible(true);
            }
        });
    }
private javax.swing.JButton btnSortRestaurants;
    private javax.swing.JButton btnSortReviews;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblAverageRating;
    private javax.swing.JTable tblOutput2;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtReview;
    private javax.swing.JTextField txtReviewerName;
    // End of variables declaration//GEN-END:variables
}

